[env:STC8H1K08]
platform = intel_mcs51
board = STC8H1K08
extra_scripts = post:upload_stcgal.py
custom_stcgal_protocol = stc8g
custom_stcgal_baud = 38400
custom_stcgal_trim = 11059.2
build_flags =
    -I../../..//core
    -I../../..//hal
    -I../../..//drivers
    -I../../..//board/stc8h1k08_tssop20_demo
    -DSTC8H_CONFIG_INCLUDE=\"board_config.h\"
    -DSTC8H_PINS_INCLUDE=\"board_pins.h\"
    -DDRV_TM1637_DELAY_US=50u
