[env:STC8H1K08]
platform = intel_mcs51
board = STC8H1K08
extra_scripts = post:upload_stcgal.py
custom_stcgal_protocol = stc8g
custom_stcgal_baud = 38400
custom_stcgal_trim = 11059.2
build_flags =
    -I../../..//core
    -I../../..//hal
    -I../../..//drivers
    -I../../..//protocols
    -I../../..//board/stc8h1k08_tssop20_demo
    -DSTC8H_CONFIG_INCLUDE=\"board_config.h\"
    -DSTC8H_PINS_INCLUDE=\"board_pins.h\"
    -DPROTO_RF_LINK_FIXED_PAYLOAD_LEN=11
    -DPROTO_RF_LINK_ENABLE_SET_IDS=1
    -DPROTO_RF_LINK_ENABLE_SEND_DATA_FIXED=1
    -DPROTO_RF_LINK_ENABLE_POLL_DATA_FIXED=1
    -DPROTO_RF_LINK_ENABLE_PACKET_ARG_CHECK=0
    -DPROTO_RF_LINK_ENABLE_INIT_TIMEOUT_FIELDS=0
    -DPROTO_RF_LINK_INCLUDE_TIMEOUT_FIELDS=0
    -DPROTO_RF_LINK_ENABLE_SEND_DATA_FIXED_TRACK_ACK=0
    -DPROTO_RF_LINK_ENABLE_POLL_DATA_FIXED_TRACK_LINK=0
    -DPROTO_RF_LINK_ENABLE_RESET=0
    -DPROTO_RF_LINK_ENABLE_TICK=0
    -DPROTO_RF_LINK_ENABLE_CONNECT=0
    -DPROTO_RF_LINK_ENABLE_SEND_DATA=0
    -DPROTO_RF_LINK_ENABLE_SEND_STATUS=0
    -DPROTO_RF_LINK_ENABLE_SEND_HEARTBEAT=0
    -DPROTO_RF_LINK_ENABLE_POLL=0
    -DPROTO_RF_LINK_ENABLE_GET_STATE=0
    -DDRV_NRF24L01_ENABLE_ARG_CHECK=0
    -DDRV_NRF24L01_ENABLE_ADDRESS_API=0
    -DDRV_NRF24L01_ENABLE_PIPE0_FIXED_API=1
    -DDRV_NRF24L01_ENABLE_READ_FIFO_STATUS=0
    -DDRV_NRF24L01_ENABLE_READ_OBSERVE_TX=0
    -DDRV_NRF24L01_ENABLE_READ_STATUS=0
    -DDRV_NRF24L01_ENABLE_ENTER_RX=0
    -DDRV_NRF24L01_ENABLE_ENTER_STANDBY=0
    -DDRV_NRF24L01_ENABLE_READ_PAYLOAD=0
    -DDRV_NRF24L01_ENABLE_RAW_API=0
    -DDRV_NRF24L01_ENABLE_DYNAMIC_PAYLOAD=0
    -DDRV_NRF24L01_ENABLE_ACK_PAYLOAD=0
