[env]
platform = intel_mcs51
board = STC8H1K08
extra_scripts = post:upload_stcgal.py
custom_stcgal_protocol = stc8g
custom_stcgal_baud = 38400
custom_stcgal_trim = 11059.2
build_flags =
    -I../../..//core
    -I../../..//hal
    -I../../..//board/stc8h1k08_tssop20_demo
    -DSTC8H_CONFIG_INCLUDE=\"board_config.h\"
    -DSTC8H_PINS_INCLUDE=\"board_pins.h\"
    -DBOARD_EEPROM_TEST_ADDR=0x0000u
    -DBOARD_EEPROM_TEST_SIZE=512u

[env:STC8H1K08]
build_flags =
    ${env.build_flags}
    -DBOARD_EEPROM_TEST_ENABLE=0

[env:STC8H1K08_write_test]
build_flags =
    ${env.build_flags}
    -DBOARD_EEPROM_TEST_ENABLE=1
