[env:STC8H8K64U]
platform = intel_mcs51
board = STC8H8K64U
board_upload.maximum_size = 65535
extra_scripts = post:../upload_stcgal.py
custom_stcgal_protocol = stc8g
custom_stcgal_baud = 38400
custom_stcgal_trim = 11059.2
build_flags =
    -I../../../core
    -I../../../hal
    -I../../../board/stc8h8k64u_lqfp48_base
    -DSTC8H_CONFIG_INCLUDE=\"board_config.h\"
    -DSTC8H_PINS_INCLUDE=\"board_pins.h\"
    -DSTC8H_UART_ENABLE_UART2=1
