[env:STC8H8K64U]
platform = intel_mcs51
board = STC8H8K64U
board_upload.maximum_size = 65535
extra_scripts =
    pre:link_bootloader.py
    post:../patch_h8k64u_ota_reset_stub.py
    post:../upload_stcgal.py
custom_stcgal_protocol = stc8g
custom_stcgal_baud = 38400
custom_stcgal_trim = 11059.2
build_flags =
    --stack-auto
    -I../../../core
    -I../../../hal
    -I../../../drivers
    -I../../../protocols
    -I../../../utils
    -Isrc
    -I../../../board/stc8h8k64u_lqfp48_base
    -DSTC8H_CONFIG_INCLUDE=\"boot_config.h\"
    -DSTC8H_PINS_INCLUDE=\"board_pins.h\"
    -DSTC8H_UART_ENABLE_UART2=1
    -DSTC8H_UART_ENABLE_WRITE_RAM=0
    -DSTC8H_UART_ENABLE_WRITE_CODE=0
    -DSTC8H_OTA_APP_LIMIT=0xB3FFu
    -DSTC8H_OTA_FORMAT_ENABLE_MANIFEST_ENCODE=0
    -DSTC8H_OTA_PARAMS_STORE_ENABLE_MARK_APP_VALID=0
    -DSTC8H_OTA_ENABLE_SHOULD_ENTER_BOOTLOADER=0
    -DUTIL_CRC32_ENABLE_ONESHOT=0
    -DSTC8H_IAP_PROGRAM_APP_LIMIT=0xB3FFu
    -DSTC8H_IAP_PROGRAM_ENABLE=1
    -DSTC8H_IAP_OTA_PARAMS_ENABLE=1
