[env:STC8H8K64U]
platform = intel_mcs51
board = STC8H8K64U
board_upload.maximum_size = 65535
build_flags =
    -I../../../core
    -I../../../hal
    -I../../../board/stc8h8k64u_lqfp48_base
    -DSTC8H_CONFIG_INCLUDE=\"board_config.h\"
    -DSTC8H_PINS_INCLUDE=\"board_pins.h\"
